// <auto-generated />
using System;
using Backend.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(FideliumContext))]
    partial class FideliumContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Service.Models.Cliente", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DeleteDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Instagram")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Instagram = "@danielobregon02",
                            IsDeleted = false,
                            Telefono = "+54 9 3498 455605",
                            UsuarioID = 8
                        },
                        new
                        {
                            ID = 2,
                            DeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Instagram = "@lucia.nwn_",
                            IsDeleted = false,
                            Telefono = "+54 9 3498 416195",
                            UsuarioID = 9
                        },
                        new
                        {
                            ID = 3,
                            DeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Instagram = "@test",
                            IsDeleted = true,
                            Telefono = "+12 3 4567 890123",
                            UsuarioID = 10
                        });
                });

            modelBuilder.Entity("Service.Models.Notificacion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CompraServicioID")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaGenerada")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ID");

                    b.HasIndex("CompraServicioID");

                    b.ToTable("Notificaciones");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CompraServicioID = 1,
                            Estado = 1,
                            FechaGenerada = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            ID = 2,
                            CompraServicioID = 2,
                            Estado = 0,
                            FechaGenerada = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            ID = 6,
                            CompraServicioID = 6,
                            Estado = 0,
                            FechaGenerada = new DateTime(2025, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = true
                        });
                });

            modelBuilder.Entity("Service.Models.Service.Models.CompraServicio", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ClienteID")
                        .HasColumnType("int");

                    b.Property<string>("ComentarioFeedback")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<int>("EmpleadoID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRecordatorio")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("FeedbackRecibido")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NotasVentaInternas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("ClienteID");

                    b.HasIndex("EmpleadoID");

                    b.ToTable("ComprasServicios");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ClienteID = 1,
                            ComentarioFeedback = "Excelente producto.",
                            CreatedAt = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Upgrade de GPU",
                            EmpleadoID = 1,
                            FechaCompra = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaRecordatorio = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FeedbackRecibido = true,
                            IsDeleted = false,
                            Nombre = "Gigabyte RTX 3050Ti",
                            NotasVentaInternas = "Buscaba jugar CSGO, se llevó esta por presupuesto."
                        },
                        new
                        {
                            ID = 2,
                            ClienteID = 1,
                            ComentarioFeedback = "",
                            CreatedAt = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Instalación limpia",
                            EmpleadoID = 5,
                            FechaCompra = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaRecordatorio = new DateTime(2025, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FeedbackRecibido = false,
                            IsDeleted = false,
                            Nombre = "Instalación Windows 11",
                            NotasVentaInternas = "PC vieja, chequear que no tire BSOD."
                        },
                        new
                        {
                            ID = 6,
                            ClienteID = 3,
                            ComentarioFeedback = "",
                            CreatedAt = new DateTime(2025, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "",
                            EmpleadoID = 2,
                            FechaCompra = new DateTime(2025, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaRecordatorio = new DateTime(2025, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FeedbackRecibido = false,
                            IsDeleted = true,
                            Nombre = "SSD NVMe 1TB",
                            NotasVentaInternas = "Test de borrado"
                        });
                });

            modelBuilder.Entity("Service.Models.Usuario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DNI")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DeleteDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DNI = "46997850",
                            DeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "martingarate0@gmail.com",
                            IsDeleted = false,
                            Nombre = "Martin Garte",
                            TipoUsuario = 0
                        },
                        new
                        {
                            ID = 2,
                            DNI = "39144832",
                            DeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "leonelarrieta@gmail.com",
                            IsDeleted = false,
                            Nombre = "Leonel Arrieta",
                            TipoUsuario = 0
                        },
                        new
                        {
                            ID = 3,
                            DNI = "46447189",
                            DeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "valentinomachado@gmail.com",
                            IsDeleted = false,
                            Nombre = "Valentino Machado",
                            TipoUsuario = 0
                        },
                        new
                        {
                            ID = 4,
                            DNI = "123456789",
                            DeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "testdelete@gmail.com",
                            IsDeleted = true,
                            Nombre = "Test Delete",
                            TipoUsuario = 0
                        },
                        new
                        {
                            ID = 5,
                            DNI = "41287827",
                            DeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "corradicande@gmail.com",
                            IsDeleted = false,
                            Nombre = "Candela Agustina Corradi",
                            TipoUsuario = 1
                        },
                        new
                        {
                            ID = 6,
                            DNI = "40317292",
                            DeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ximenagorosito0@gmail.com",
                            IsDeleted = false,
                            Nombre = "Ximena Gorosito",
                            TipoUsuario = 1
                        },
                        new
                        {
                            ID = 7,
                            DNI = "123456781",
                            DeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "testdelete2@gmail.com",
                            IsDeleted = true,
                            Nombre = "Test2 Delete",
                            TipoUsuario = 1
                        },
                        new
                        {
                            ID = 8,
                            DNI = "46133497",
                            DeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "danielobregon621@gmail.com",
                            IsDeleted = false,
                            Nombre = "Daniel Alejandro Obregon",
                            TipoUsuario = 2
                        },
                        new
                        {
                            ID = 9,
                            DNI = "45641614",
                            DeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lucilencina6@gmail.com",
                            IsDeleted = false,
                            Nombre = "Lucia Lencina",
                            TipoUsuario = 2
                        },
                        new
                        {
                            ID = 10,
                            DNI = "123456782",
                            DeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "testdelete3@gmail.com",
                            IsDeleted = true,
                            Nombre = "Test3 Delete",
                            TipoUsuario = 2
                        });
                });

            modelBuilder.Entity("Service.Models.Cliente", b =>
                {
                    b.HasOne("Service.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Service.Models.Notificacion", b =>
                {
                    b.HasOne("Service.Models.Service.Models.CompraServicio", "CompraServicio")
                        .WithMany()
                        .HasForeignKey("CompraServicioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompraServicio");
                });

            modelBuilder.Entity("Service.Models.Service.Models.CompraServicio", b =>
                {
                    b.HasOne("Service.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Service.Models.Usuario", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Empleado");
                });
#pragma warning restore 612, 618
        }
    }
}
