// <auto-generated />
using System;
using Backend.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(FideliumContext))]
    partial class FideliumContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Service.Models.Cliente", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DeleteDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Instagram")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Instagram = "@danielobregon02",
                            IsDeleted = false,
                            Telefono = "+54 9 3498 455605",
                            UsuarioID = 8
                        },
                        new
                        {
                            ID = 2,
                            DeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Instagram = "@lucia.nwn_",
                            IsDeleted = false,
                            Telefono = "+54 9 3498 416195",
                            UsuarioID = 9
                        },
                        new
                        {
                            ID = 3,
                            DeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Instagram = "@test",
                            IsDeleted = true,
                            Telefono = "+12 3 4567 890123",
                            UsuarioID = 10
                        });
                });

            modelBuilder.Entity("Service.Models.CompraServicio", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ClienteID")
                        .HasColumnType("int");

                    b.Property<string>("ComentarioFeedback")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DeleteDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<int>("EmpleadoID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.HasIndex("ClienteID");

                    b.HasIndex("EmpleadoID");

                    b.ToTable("ComprasServicios");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ClienteID = 1,
                            ComentarioFeedback = "Excelente producto y muy buena atención al público. Muy recomendado.",
                            CreatedAt = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Upgrade de GPU para mejorar rendimiento en gaming y rendering",
                            EmpleadoID = 1,
                            FechaCompra = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Nombre = "Compra de Tarjeta Gráfica Gigabyte RTX 3050Ti",
                            UpdateAt = new DateTime(2025, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2,
                            ClienteID = 1,
                            ComentarioFeedback = "Trabajo muy profesional, PC corriendo perfectamente",
                            CreatedAt = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Instalación limpia de Windows 11 Pro con drivers actualizados",
                            EmpleadoID = 5,
                            FechaCompra = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Nombre = "Servicio de Instalación de SO Windows 11 Pro",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3,
                            ClienteID = 2,
                            ComentarioFeedback = "Excelente servicio, la PC ahora funciona mucho más rápido",
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Limpieza a fondo interna y externa, cambio de pasta térmica",
                            EmpleadoID = 2,
                            FechaCompra = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Nombre = "Servicio de Limpieza Profesional de PC",
                            UpdateAt = new DateTime(2025, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 4,
                            ClienteID = 2,
                            ComentarioFeedback = "Proceso rápido y eficiente. Ahora puedo correr múltiples aplicaciones sin lag",
                            CreatedAt = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Instalación de módulos RAM Corsair Vengeance para multitarea",
                            EmpleadoID = 6,
                            FechaCompra = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Nombre = "Upgrade de RAM a 32GB DDR4",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 5,
                            ClienteID = 2,
                            ComentarioFeedback = "Muy útil, ahora tengo mi red segura y optimizada",
                            CreatedAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Asesoramiento en configuración de red doméstica y seguridad",
                            EmpleadoID = 3,
                            FechaCompra = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Nombre = "Consultoría de Configuración de Red",
                            UpdateAt = new DateTime(2025, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 6,
                            ClienteID = 3,
                            ComentarioFeedback = "Servicio eliminado - prueba de soft delete",
                            CreatedAt = new DateTime(2025, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeleteDate = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Instalación de unidad SSD rápida para sistema operativo",
                            EmpleadoID = 2,
                            FechaCompra = new DateTime(2025, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = true,
                            Nombre = "Compra de SSD NVMe 1TB",
                            UpdateAt = new DateTime(2025, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Service.Models.Notificacion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ClienteID")
                        .HasColumnType("int");

                    b.Property<string>("ComentarioEmpleado")
                        .HasColumnType("longtext");

                    b.Property<int>("CompraServicioID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DeleteDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DiasParaRecordatorio")
                        .HasColumnType("int");

                    b.Property<int>("EmpleadoID")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaGenerada")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaRecordatorio")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.HasIndex("ClienteID");

                    b.HasIndex("CompraServicioID");

                    b.HasIndex("EmpleadoID");

                    b.ToTable("Notificaciones");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ClienteID = 1,
                            ComentarioEmpleado = "Seguimiento post-venta de GPU, verificar compatibilidad y rendimiento",
                            CompraServicioID = 1,
                            CreateAt = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiasParaRecordatorio = 7,
                            EmpleadoID = 1,
                            Estado = 0,
                            FechaGenerada = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaRecordatorio = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2,
                            ClienteID = 1,
                            ComentarioEmpleado = "Verificar que la instalación de Windows 11 Pro se completó correctamente",
                            CompraServicioID = 2,
                            CreateAt = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiasParaRecordatorio = 3,
                            EmpleadoID = 5,
                            Estado = 1,
                            FechaGenerada = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaRecordatorio = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            UpdateAt = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3,
                            ClienteID = 2,
                            ComentarioEmpleado = "Follow-up de limpieza de PC, preguntar si hay mejora en temperatura",
                            CompraServicioID = 3,
                            CreateAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiasParaRecordatorio = 14,
                            EmpleadoID = 2,
                            Estado = 1,
                            FechaGenerada = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaRecordatorio = new DateTime(2025, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            UpdateAt = new DateTime(2025, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 4,
                            ClienteID = 2,
                            ComentarioEmpleado = "Verificación del upgrade de RAM, evaluar satisfacción del cliente",
                            CompraServicioID = 4,
                            CreateAt = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiasParaRecordatorio = 10,
                            EmpleadoID = 6,
                            Estado = 0,
                            FechaGenerada = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaRecordatorio = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 5,
                            ClienteID = 2,
                            ComentarioEmpleado = "Evaluación de satisfacción post-consultoría de configuración de red",
                            CompraServicioID = 5,
                            CreateAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiasParaRecordatorio = 30,
                            EmpleadoID = 3,
                            Estado = 0,
                            FechaGenerada = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaRecordatorio = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 6,
                            ClienteID = 3,
                            ComentarioEmpleado = "Notificación eliminada - prueba de soft delete",
                            CompraServicioID = 6,
                            CreateAt = new DateTime(2025, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeleteDate = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiasParaRecordatorio = 5,
                            EmpleadoID = 2,
                            Estado = 0,
                            FechaGenerada = new DateTime(2025, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaRecordatorio = new DateTime(2025, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = true,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Service.Models.Usuario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DNI")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DeleteDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DNI = "46997850",
                            DeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "martingarate0@gmail.com",
                            IsDeleted = false,
                            Nombre = "Martin Garte",
                            TipoUsuario = 0
                        },
                        new
                        {
                            ID = 2,
                            DNI = "39144832",
                            DeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "leonelarrieta@gmail.com",
                            IsDeleted = false,
                            Nombre = "Leonel Arrieta",
                            TipoUsuario = 0
                        },
                        new
                        {
                            ID = 3,
                            DNI = "46447189",
                            DeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "valentinomachado@gmail.com",
                            IsDeleted = false,
                            Nombre = "Valentino Machado",
                            TipoUsuario = 0
                        },
                        new
                        {
                            ID = 4,
                            DNI = "123456789",
                            DeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "testdelete@gmail.com",
                            IsDeleted = true,
                            Nombre = "Test Delete",
                            TipoUsuario = 0
                        },
                        new
                        {
                            ID = 5,
                            DNI = "41287827",
                            DeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "corradicande@gmail.com",
                            IsDeleted = false,
                            Nombre = "Candela Agustina Corradi",
                            TipoUsuario = 1
                        },
                        new
                        {
                            ID = 6,
                            DNI = "40317292",
                            DeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ximenagorosito0@gmail.com",
                            IsDeleted = false,
                            Nombre = "Ximena Gorosito",
                            TipoUsuario = 1
                        },
                        new
                        {
                            ID = 7,
                            DNI = "123456781",
                            DeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "testdelete2@gmail.com",
                            IsDeleted = true,
                            Nombre = "Test2 Delete",
                            TipoUsuario = 1
                        },
                        new
                        {
                            ID = 8,
                            DNI = "46133497",
                            DeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "danielobregon621@gmail.com",
                            IsDeleted = false,
                            Nombre = "Daniel Alejandro Obregon",
                            TipoUsuario = 2
                        },
                        new
                        {
                            ID = 9,
                            DNI = "45641614",
                            DeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lucilencina6@gmail.com",
                            IsDeleted = false,
                            Nombre = "Lucia Lencina",
                            TipoUsuario = 2
                        },
                        new
                        {
                            ID = 10,
                            DNI = "123456782",
                            DeleteDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "testdelete3@gmail.com",
                            IsDeleted = true,
                            Nombre = "Test3 Delete",
                            TipoUsuario = 2
                        });
                });

            modelBuilder.Entity("Service.Models.Cliente", b =>
                {
                    b.HasOne("Service.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Service.Models.CompraServicio", b =>
                {
                    b.HasOne("Service.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Service.Models.Usuario", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("Service.Models.Notificacion", b =>
                {
                    b.HasOne("Service.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Service.Models.CompraServicio", "CompraServicio")
                        .WithMany()
                        .HasForeignKey("CompraServicioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Service.Models.Usuario", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("CompraServicio");

                    b.Navigation("Empleado");
                });
#pragma warning restore 612, 618
        }
    }
}
